//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.salaries = new HashSet<salary>();
        }
    
        public int empId { get; set; }
        public string empName { get; set; }
        public string empPhone { get; set; }
        public string empEmail { get; set; }
        public string empAddress { get; set; }
        public System.DateTime joiningDate { get; set; }
        public string empIsActive { get; set; }
        public string empGender { get; set; }
        public string empSkill { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salary> salaries { get; set; }
        public virtual user user { get; set; }
        public virtual department department { get; set; }
        public virtual designation designation { get; set; }
        public virtual usertype usertype { get; set; }
    }
}
