//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMSdbContext1 : DbContext
    {
        public HRMSdbContext1()
            : base("name=HRMSdbContext1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<designation> designations { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<payroll> payrolls { get; set; }
        public virtual DbSet<payslip> payslips { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usertype> usertypes { get; set; }
    }
}
