//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class payslip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payslip()
        {
            this.payrolls = new HashSet<payroll>();
        }
    
        public int payslipId { get; set; }
        public System.DateTime payslipDate { get; set; }
        public double addition { get; set; }
        public double deduction { get; set; }
        public string genarate { get; set; }
        public double basic { get; set; }
        public double ca { get; set; }
        public double ha { get; set; }
        public int salId { get; set; }
    
        public virtual salary salary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll> payrolls { get; set; }
    }
}
