//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int empId { get; set; }
        public string userId { get; set; }
        public string pass { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
